### ISSUE TITLE
Could you share the code of you Android project?

### ISSUE THREAD

**Issue by xh894337710** [luiseduve/exciteometer#1]
Could you share the code of you Android project? I am very interested in it and want to learn it.

**Comment by luisqtr** [comment]
Hi @xh894337710. Unfortunately the code of the ExciteOMeter-Devices is not at hand. But it was heavily based on the on the [Polar SDK](https://github.com/polarofficial/polar-ble-sdk) expanded with the protocol [LSL](https://github.com/sccn/labstreaminglayer).

**Comment by luisqtr** [comment]
The Android project to compile Excite-O-Meter Devices (Android version) was made available in this repository:

https://github.com/luisqtr/exciteometer-devices-android
