### ISSUE TITLE
ScreenRecorder setup

### ISSUE THREAD

**Issue by 99bits** [luiseduve/exciteometer#11]
Hi Luis,

I am testing the project in unity 2022 and most of it is working but not the screen recording.  Do you know what this error could be.  
![ScreenRecorderSet](https://user-images.githubusercontent.com/22409112/230605494-71fcc8bd-ed07-420e-a149-d09baf467c77.jpg)

**Comment by 99bits** [comment]
Created a fresh 2022 URP project, imported the Exciteometer unity package.
and the error went away.

**Comment by luisqtr** [comment]
Hi.
Glad to know that it works properly. In the first project, make sure that the `DataLogger_Controller` has a filename configured as `Events and Markers`. Fixing the warning will also get rid of the error.

![image](https://user-images.githubusercontent.com/11824238/230713755-bb5b2343-0c37-48ed-a045-030226927b95.png)
