### ISSUE TITLE
ExciteOMeter_1.0.7.0_Test Win10 expired certificate

### ISSUE THREAD

**Issue by iroupa** [luiseduve/exciteometer#14]
I'm trying to install the latest release of ExciteOMeter_1.0.7.0_Test for Win10 ( ExciteOMeter_1.0.7_UWP.zip) but after clicking the file Add-AppDevPackage.ps1 and click on Run with Powershell, I got the following error:

. : File C:\Users\admin\Documents\WindowsPowerShell\profile.ps1 cannot be loaded because running scripts is disabled
on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\Users\admin\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
Found bundle: C:\Users\admin\Desktop\ExciteOMeter_1.0.7.0_Test\ExciteOMeter_1.0.7.0_x86.appxbundle
Found certificate: C:\Users\admin\Desktop\ExciteOMeter_1.0.7.0_Test\ExciteOMeter_1.0.7.0_x86.cer
Error: The developer certificate "C:\Users\admin\Desktop\ExciteOMeter_1.0.7.0_Test\ExciteOMeter_1.0.7.0_x86.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.
Press Enter to continue...:

As in issue #3 I think that the problem is that the certificate has expired.

Thank you for your help

Best regards

Ivo

**Comment by luisqtr** [comment]
Hi iroupa, 

Thanks for using the Excite-O-Meter and notifying about the certificate problem. I have uploaded a new version with the updated certificate here: https://github.com/luisqtr/exciteometer-devices-UWP/releases

Please try and let me know in case of problems.
I also requested new approval from Microsoft Store to make it easy to use, I'll post updates if it goes live again.

/Luis

**Comment by iroupa** [comment]
Hi luisqtr,

I was able to install ExciteOMeter_1.0.8.0_Test successfully. 

Thank you for your help.

**Comment by luisqtr** [comment]
Hi,
The Excite-O-Meter is live again in the Microsoft Store if you want to install it directly without dev steps:
https://www.microsoft.com/store/apps/9NW9MSXHTQ5M
/Luis
