### ISSUE TITLE
ExciteOMeter_0.2.9.0_Win10 expired certificate

### ISSUE THREAD

**Issue by baroquedub** [luiseduve/exciteometer#3]
Trying to install the Windows10 device (ExciteOMeter_0.2.9.0_Win10.zip from the release v1.0.1 branch), after right-clicking Add-AppDevPackage.ps1 and running PowerShell, I first get the 'Execution Policy Change' message and type Y to proceed, but then I get the following error:

`Found bundle: J:\ExciteOMeter_0.2.9.0_Win10\ExciteOMeter_0.2.9.0_Test\ExciteOMeter_0.2.9.0_x86.appxbundle
Found certificate: J:\ExciteOMeter_0.2.9.0_Win10\ExciteOMeter_0.2.9.0_Test\ExciteOMeter_0.2.9.0_x86.cer
Error: The developer certificate "J:\ExciteOMeter_0.2.9.0_Win10\ExciteOMeter_0.2.9.0_Test\ExciteOMeter_0.2.9.0_x86.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.`

I've tried on two separate computers so i assume this is not caused by an incorrect system clock, but rather that the certificate has expired.

**Comment by luisqtr** [comment]
Thanks for reporting this problem. We have uploaded a new version with the updated UWP certificate. Now you can download the file `ExciteOMeter-Devices/ExciteOMeter_0.3.0.0_Win10.zip` and it should install without problems.

**Comment by baroquedub** [comment]
Thanks. I can confirm that it now gets past that error. I seem to have an issue getting the developer status but that's another issue related to my own machine. Closing :)
