### ISSUE TITLE
Ui Extensions particle shader cause build to fail

### ISSUE THREAD

**Issue by baroquedub** [luiseduve/exciteometer#4]
Not sure if this also happens in 2019, but in Unity 2020.3.12 the Ui Extensions particle shaders cause the build to fail:
[http://baroquedub.co.uk/private/forum-images/shaders-build_failed.jpg](http://baroquedub.co.uk/private/forum-images/shaders-build_failed.jpg)

Deleting the ones prefixed as 'UI Particle' fixes the problem (they don't appear to be used in the Excite-O-Meter UI elements)
[http://baroquedub.co.uk/private/forum-images/shaders-ui-extensions.jpg](http://baroquedub.co.uk/private/forum-images/shaders-ui-extensions.jpg)

This using the UnityUIExtensions-2019-6.unitypackage (I realise this isn't your asset but leaving this here for anyone having the same issue)

**Comment by luisqtr** [comment]
Thanks @baroquedub. I will try it in a newer Unity version and see if I have the same errors. Are you using Unity's built-in 3D or URP in your project?

**Comment by baroquedub** [comment]
> Are you using Unity's built-in 3D or URP in your project?
Good point! I should have said :) I'm using URP

**Comment by luisqtr** [comment]
It seems to be an error that only happens the first time you build the project. I created a URP project in Unity 2020.3.19, the build error appeared as in your screenshot, but the .exe was created anyway. When I tried to build again (without changing anything), the errors disappeared.
