### ISSUE TITLE
Issue with Windows 10 installation

### ISSUE THREAD

**Issue by pilotbaba** [luiseduve/exciteometer#6]
Tried to follow the installation tutorial for Windows 10. I ran into the known issue of invalid certificate. 
Can you generate an new build with the updated certificate?
Is the repo live?

**Comment by luisqtr** [comment]
Hi pilotbaba,
Thanks for informing about the issue. The new build with the updated certificate can be downloaded [from the updated release].(https://github.com/luisqtr/exciteometer/releases/download/v1.1/ExciteOMeter_0.3.1.0_Win10.zip)
