### ISSUE TITLE
Awesome project.  Would love to use it, wondering if it works on latest 2021 LTS.

### ISSUE THREAD

**Issue by 99bits** [luiseduve/exciteometer#7]
I tried the project on different versions of unity 2021 LTS and it doesn't seem to work.
Have you tested it on 2021 LTS?

Cheers

**Comment by luisqtr** [comment]
Hi, unfortunately we haven't tested 2021 yet. We plan to get back to the project in the next few weeks and I will update on any info we get regarding this.

**Comment by 99bits** [comment]
That would be amazing.  Muchas Gracias

**Comment by luisqtr** [comment]
Closed in #12
