### ISSUE TITLE
Some questions regarding the heart rate sensor.

### ISSUE THREAD

**Issue by CSLVRlab-PW** [luiseduve/exciteometer#8]
Hi,

I really like the idea and would like to test run the plug-in. 
But we do not own a Polar H10 sensor at the moment.

Is it possible to use a different sensor. E.g BiosignalPlux or Polar Verity Sense sensors?

Many thanks!

**Comment by luisqtr** [comment]
Hi, 
Unfortunately it was initially designed to work with the Polar H10, the Polar may work if they use the same Bluetooth LE protocol (but we cannot test it).

The Unity plugin should work with for any incoming data using [LabStreamingLayer (LSL)](https://github.com/sccn/labstreaminglayer). But some development is needed to create the middleware that translates the data from a specific sensor to LSL. If you have someone experienced in the team, the source code of the Android middleware was released some days ago (<https://github.com/luisqtr/exciteometer-devices-android>), and we hope to get soon to add compatibility with few other sensors.
