### ISSUE TITLE
Support for Web bluetooth ?

### ISSUE THREAD

**Issue by 99bits** [luiseduve/exciteometer#9]
Would it be possible to support Web bluetooth sensors.  
There are projects that use RxJS and Web Bluetooth.  Perhaps RxJS can act like a LSL stream.
If this is possible then it would be very amazing to collect data via the web. 

https://urish.medium.com/reactive-brain-waves-af07864bb7d4
https://eegedu.com/

**Comment by luisqtr** [comment]
That looks cool, but I guess outside my scope right now.
Please let me know what I can provided in case you are interested in adapting the existing middleware.
